print("CURRICULUM VITAE")
print("Nume Prenume  Schița Ecaterina")
print("Locul nașterii Republica Moldova,municipiul Bălți")
print("Data nașterii 03.02.2005")
print("Numărul de telefon 060287187")
print("E-mail skicaekaterina@gmail.com")
print("Adresa Decebal121|2 ap.27")
print("Naționalitatea moldoveancă")
print("Stare civilă necăsătorită")
print("Calități responsabilitate,perseverență,sinceritate,răbdare,încredere,altruism")
print("Abilități capacitatea de a interacționa cu cei din jur,de a avea o comunicare fluentă și culta")
print("Limbi străine enleza-B1, germana-B1, limba rusă")
print("Hobby și ocupații hipismul,dansurile,vocalul,tenisul de masă")